# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb4f51d5b127bf993caa1dac1ccc75d960737c62db0abfbfbb65c83cd877b060a287ac2e4bd2a9dba4977b2c89e2f20b97a58edd75e30e2f82613bf427d8cba1

test:
  secret_key_base: 3a28c7ac8ee8d319e0ff0a15f79fe446b0d6574eebc232630cfcc33db19710bcf0fa68b9f6f9a4b7c811d37c222bd256370aa040dc29622678218fed84efc0a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
